name: Auto Assign to Project

on:
  issues:
    types: [opened, reopened]

env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign DevBoard
    steps:
    - name: Assign DevBoard
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'|| github.event.action == 'reopened'
      with:
        project: 'https://github.com/UTK-CS340-Fall-2020/0x432d2d/projects/1'
        column_name: 'To Do'
