name: Pylint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Deps
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint
        pip install pylint-exit
        pip install -r requirements.txt
    - name: Analyse Code
      run: |
        python3 -m pylint src > output.txt || echo $? > code.txt
        cat output.txt
        cat output.txt | grep -i rated > result.txt
    - name: Comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: $(cat result.txt)  
      with:
        msg: ${{ env.MESSAGE }}
        check_for_duplicate_msg: false  # OPTIONAL 
    - name: Return
      run:
        cat code.txt | xargs pylint-exit --error-fail
