name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint
        pip install pylint-exit
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        python3 -m pylint src || pylint-exit --error-fail $?
        if [ $? -ne 0 ]; then
          echo "An error occurred while running pylint." >&2
          exit 1
        fi
