name: UnitTest

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Deps
      run: |
        sudo apt install libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev \
        libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev \
        libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev \
        libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev \
        libxcb-xinerama0-dev libxkbcommon-dev libxkbcommon-x11-dev xvfb
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run UnitTests
      env:
        QT_DEBUG_PLUGINS: 1
      run: |
        xvfb-run --auto-servernum npm test.sh
