name: UnitTest

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Deps
      run: |
        sudo apt install libxcb-icccm4
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run UnitTests
      env:
        QT_DEBUG_PLUGINS: 1
      run: |
        ./test.sh
